---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Super Linter

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: pull_request

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        with:
          entrypoint: /bin/bash
          args: -c "pip3 --no-cache-dir install pylint-django[with_django] && /action/lib/linter.sh"
        env:
          DEFAULT_BRANCH: develop
          VALIDATE_ALL_CODEBASE: false
